package com.mnemolith.config;

import net.neoforged.neoforge.common.ModConfigSpec;

/**
 * Common config ({@code mnemolith-common.toml}). Loaded on the physical client and the dedicated server.
 */
public final class CommonConfig {
    public static final ModConfigSpec.DoubleValue RECOLLECTION_STORM_THRESHOLD;
    public static final ModConfigSpec.IntValue PRESSURE_SOFT_CAP;
    public static final ModConfigSpec.IntValue IMPRINT_NODE_WEIGHT;
    public static final ModConfigSpec.DoubleValue STORM_ATTEMPT_CHANCE;
    public static final ModConfigSpec.BooleanValue STRUCTURES_ENABLED;
    public static final ModConfigSpec.IntValue STRUCTURE_SPACING;
    public static final ModConfigSpec.BooleanValue COMPOSITION_ENABLED;
    public static final ModConfigSpec.IntValue MAX_IMPRINTS_PER_CHUNK;
    public static final ModConfigSpec.BooleanValue WRITE_IMPRINTS;
    public static final ModConfigSpec.IntValue WRITE_DEBOUNCE_TICKS;
    public static final ModConfigSpec.BooleanValue WRITE_DEATH;
    public static final ModConfigSpec.BooleanValue WRITE_EXPLOSION;
    public static final ModConfigSpec.BooleanValue WRITE_FALL;
    public static final ModConfigSpec.BooleanValue WRITE_BUILD;
    public static final ModConfigSpec.DoubleValue FALL_DISTANCE_MIN;
    public static final ModConfigSpec.IntValue EXTRACTION_DURABILITY_COST;
    public static final ModConfigSpec.IntValue EXTRACTION_COOLDOWN_TICKS;
    public static final ModConfigSpec.IntValue FAILURE_PRESSURE_SPIKE;
    public static final ModConfigSpec.IntValue INSTABILITY_DECAY;
    public static final ModConfigSpec.IntValue INSTABILITY_DECAY_TICKS;
    public static final ModConfigSpec.IntValue QUIET_FADE_TICKS;
    public static final ModConfigSpec.IntValue VEIN_SHIMMER_TICKS;
    public static final ModConfigSpec.BooleanValue ALLOW_AMBIENT_PRESSURE;
    public static final ModConfigSpec.IntValue SATURATED_THRESHOLD;
    public static final ModConfigSpec.IntValue OVERLOADED_THRESHOLD;
    public static final ModConfigSpec.IntValue FRACTURE_THRESHOLD;
    public static final ModConfigSpec.IntValue MUTE_RADIUS_CHUNKS;
    public static final ModConfigSpec.BooleanValue CATALOG_ENABLED;
    public static final ModConfigSpec.BooleanValue DISCOVERY_HINTS;
    public static final ModConfigSpec.BooleanValue ECHO_STRIDER_ENABLED;
    public static final ModConfigSpec.BooleanValue ARCHIVIST_ENABLED;
    public static final ModConfigSpec.BooleanValue MOMENT_REPLICANT_ENABLED;
    public static final ModConfigSpec.DoubleValue ECHO_STRIDER_DAMAGE;
    public static final ModConfigSpec.DoubleValue ARCHIVIST_DAMAGE;
    public static final ModConfigSpec.DoubleValue REPLICANT_DAMAGE;
    public static final ModConfigSpec.IntValue ARCHIVIST_STEAL_COOLDOWN;
    public static final ModConfigSpec.IntValue ECHO_STRIDER_SPAWN_WEIGHT;
    public static final ModConfigSpec.IntValue ARCHIVIST_SPAWN_WEIGHT;
    public static final ModConfigSpec.IntValue REPLICANT_SPAWN_WEIGHT;
    public static final ModConfigSpec.IntValue ECHO_STRIDER_MIN_PRESSURE;
    public static final ModConfigSpec.IntValue ARCHIVIST_MIN_PRESSURE;
    public static final ModConfigSpec.IntValue REPLICANT_MIN_PRESSURE;
    public static final ModConfigSpec.IntValue SENSOR_INTERVAL;
    public static final ModConfigSpec.BooleanValue ARCHIVAL_VEINS_ENABLED;
    public static final ModConfigSpec.IntValue ARCHIVAL_VEIN_CHANCE;
    public static final ModConfigSpec.IntValue ARCHIVAL_VEIN_MIN_Y;
    public static final ModConfigSpec.IntValue ARCHIVAL_VEIN_MAX_Y;
    public static final ModConfigSpec.IntValue ARCHIVAL_VEIN_SIZE;
    public static final ModConfigSpec.IntValue ARCHIVAL_BLEED;
    public static final ModConfigSpec.IntValue ARCHIVAL_BLEED_CAP;
    public static final ModConfigSpec.BooleanValue MUTE_POCKETS_ENABLED;
    public static final ModConfigSpec.IntValue MUTE_POCKET_CHANCE;
    public static final ModConfigSpec.IntValue MUTE_POCKET_MIN_Y;
    public static final ModConfigSpec.IntValue MUTE_POCKET_MAX_Y;
    public static final ModConfigSpec.BooleanValue OBSERVATORY_ENABLED;
    public static final ModConfigSpec.BooleanValue ARCHIVIST_OBSERVATORY_BIAS;
    public static final ModConfigSpec.BooleanValue STRIDER_PATH_BIAS;
    public static final ModConfigSpec.BooleanValue ECHOES_ENABLED;
    public static final ModConfigSpec.IntValue ECHO_RECORD_SECONDS;
    public static final ModConfigSpec.IntValue ECHO_MAX_PER_PLAYER;
    public static final ModConfigSpec.IntValue ECHO_ACTIVATE_RANGE;
    public static final ModConfigSpec.IntValue ECHO_POSSESS_RANGE;
    public static final ModConfigSpec.DoubleValue ECHO_MAX_HEALTH;
    public static final ModConfigSpec.IntValue ECHO_DEATH_PRESSURE_SPIKE;
    public static final ModConfigSpec.IntValue ECHO_SHELL_AGGRO_RADIUS;
    public static final ModConfigSpec.IntValue ECHO_MINE_RADIUS;
    public static final ModConfigSpec.IntValue ECHO_MINE_MAX_RADIUS;
    public static final ModConfigSpec.IntValue ECHO_TUNNEL_MAX;
    public static final ModConfigSpec.IntValue ECHO_DEPOSIT_FREE_SLOTS;
    public static final ModConfigSpec.BooleanValue ECHO_BUILD_CLEARS_TERRAIN;
    public static final ModConfigSpec.IntValue ECHO_SCAN_BUDGET;
    public static final ModConfigSpec.IntValue ECHO_PATH_BUDGET;
    public static final ModConfigSpec.BooleanValue ECHO_MOB_AGGRO;
    public static final ModConfigSpec.IntValue ECHO_FLEE_DISTANCE;
    public static final ModConfigSpec.IntValue ECHO_FLEE_SAFE_TICKS;
    public static final ModConfigSpec.BooleanValue ECHO_ARCHIVIST_STEAL;
    public static final ModConfigSpec.IntValue ECHO_ARCHIVIST_STEAL_MAX;
    public static final ModConfigSpec.IntValue ECHO_REPLICANT_MIMIC_TICKS;
    public static final ModConfigSpec.IntValue ECHO_REPLICANT_UNDO_MAX;
    public static final ModConfigSpec.BooleanValue ECHO_STRIDER_SHADOW;
    public static final ModConfigSpec.IntValue ECHO_MAX_PER_PLAYER_CAP;
    public static final ModConfigSpec.IntValue ECHO_RECORD_BONUS_SECONDS;
    public static final ModConfigSpec.IntValue ECHO_RECORD_UPGRADE_MAX;
    public static final ModConfigSpec.DoubleValue ECHO_STURDY_HEALTH_BONUS;
    public static final ModConfigSpec.IntValue ECHO_STURDY_UPGRADE_MAX;
    public static final ModConfigSpec.IntValue ECHO_FARM_MAX_RADIUS;
    public static final ModConfigSpec.IntValue ECHO_FARM_POLL_TICKS;
    public static final ModConfigSpec.IntValue ECHO_WORK_IMPRINT_EVERY;
    public static final ModConfigSpec.IntValue ECHO_WORK_INSTABILITY;
    public static final ModConfigSpec.DoubleValue ECHO_MISFIRE_CHANCE;
    public static final ModConfigSpec.BooleanValue ECHO_FRACTURE_STOPS;
    public static final ModConfigSpec.IntValue ECHO_FOLLOW_LOST_DISTANCE;
    public static final ModConfigSpec SPEC;

    static {
        ModConfigSpec.Builder builder = new ModConfigSpec.Builder();

        SpecValues.section(builder, "difficulty", "Thresholds that decide when recollection becomes dangerous.");
        RECOLLECTION_STORM_THRESHOLD = SpecValues.decimal(builder, "recollectionStormThreshold", "Multiplier on the saturated, overloaded, and fracture thresholds. Each scaled threshold is capped at pressureSoftCap, so fracture stays reachable. Recollection storms themselves are not implemented yet.", 1.0D, 0.1D, 10.0D);
        PRESSURE_SOFT_CAP = SpecValues.integer(builder, "pressureSoftCap", "Soft cap for memory pressure accumulated from imprints in loaded chunks.", 100, 1, 10_000);
        builder.pop();

        SpecValues.section(builder, "spawnRates", "Relative weights for future imprint nodes and storm attempts. Worldgen does not use these yet.");
        IMPRINT_NODE_WEIGHT = SpecValues.integer(builder, "imprintNodeWeight", "Reserved, not used yet. Relative weight of imprint-bearing nodes when structures are placed.", 4, 0, 100);
        STORM_ATTEMPT_CHANCE = SpecValues.decimal(builder, "stormAttemptChance", "Reserved, not used yet: recollection storms are not implemented. Chance, from 0.0 to 1.0, that a pressure check attempts a storm.", 0.02D, 0.0D, 1.0D);
        builder.pop();

        SpecValues.section(builder, "worldGen", "Structure placement defaults. Changing these takes effect the next time a world loads.");
        STRUCTURES_ENABLED = SpecValues.boolRestart(builder, "structuresEnabled", "Whether the chronicle observatory may generate. Veins and mute pockets have their own toggles.", true);
        STRUCTURE_SPACING = SpecValues.integerRestart(builder, "structureSpacing", "Documented spacing, in chunks, of the chronicle observatory. The structure set json uses 32 and a separation of 12. Editing this number does not move structures.", 32, 8, 256);
        ARCHIVAL_VEINS_ENABLED = SpecValues.bool(builder, "archivalVeinsEnabled", "Whether archival veins may generate. The biome modifier uses #minecraft:is_overworld. The Y range keeps them underground.", true);
        ARCHIVAL_VEIN_CHANCE = SpecValues.integer(builder, "archivalVeinChance", "Chance, out of 100, that a chunk attempts an archival vein.", 8, 0, 100);
        ARCHIVAL_VEIN_MIN_Y = SpecValues.integer(builder, "archivalVeinMinY", "Lowest Y of an archival vein.", -48, -64, 320);
        ARCHIVAL_VEIN_MAX_Y = SpecValues.integer(builder, "archivalVeinMaxY", "Highest Y of an archival vein.", 32, -64, 320);
        ARCHIVAL_VEIN_SIZE = SpecValues.integer(builder, "archivalVeinSize", "Length, in blocks, of one archival vein.", 7, 3, 16);
        ARCHIVAL_BLEED = SpecValues.integer(builder, "archivalBleed", "Pressure added per archival stratum block when the chunk's pressure is scored.", 1, 0, 20);
        ARCHIVAL_BLEED_CAP = SpecValues.integer(builder, "archivalBleedCap", "Most stratum blocks that contribute pressure in one chunk.", 6, 0, 64);
        MUTE_POCKETS_ENABLED = SpecValues.bool(builder, "mutePocketsEnabled", "Whether mute pockets may generate. Placed mute stone uses the same write suppression as a crafted mute stone.", true);
        MUTE_POCKET_CHANCE = SpecValues.integer(builder, "mutePocketChance", "Chance, out of 100, that a chunk attempts a mute pocket.", 4, 0, 100);
        MUTE_POCKET_MIN_Y = SpecValues.integer(builder, "mutePocketMinY", "Lowest Y of a mute pocket.", -32, -64, 320);
        MUTE_POCKET_MAX_Y = SpecValues.integer(builder, "mutePocketMaxY", "Highest Y of a mute pocket.", 48, -64, 320);
        OBSERVATORY_ENABLED = SpecValues.boolRestart(builder, "observatoryEnabled", "Whether chronicle observatories may generate. Also requires structuresEnabled.", true);
        ARCHIVIST_OBSERVATORY_BIAS = SpecValues.bool(builder, "archivistObservatoryBias", "Whether an archivist's natural pressure gate is lower in and near an observatory chunk.", true);
        STRIDER_PATH_BIAS = SpecValues.bool(builder, "striderPathBias", "Whether an echo strider's natural pressure gate is lower in a chunk that already holds a path imprint.", true);
        builder.pop();

        SpecValues.section(builder, "gameplay", "Player-facing memory rules for writing, extraction, and composition.");
        COMPOSITION_ENABLED = SpecValues.bool(builder, "compositionEnabled", "Whether players may compose extracted imprints.", true);
        MAX_IMPRINTS_PER_CHUNK = SpecValues.integer(builder, "maxImprintsPerChunk", "Maximum imprints stored on a single chunk. Lowest intensity is dropped first.", 8, 1, 64);
        WRITE_IMPRINTS = SpecValues.bool(builder, "writeImprints", "Whether world events write imprints.", true);
        WRITE_DEBOUNCE_TICKS = SpecValues.integer(builder, "writeDebounceTicks", "Ticks that must pass before another build or redstone imprint can be written in the same chunk.", 80, 1, 200);
        WRITE_DEATH = SpecValues.bool(builder, "writeDeath", "Whether a death writes a death imprint.", true);
        WRITE_EXPLOSION = SpecValues.bool(builder, "writeExplosion", "Whether an explosion writes an explosion imprint.", true);
        WRITE_FALL = SpecValues.bool(builder, "writeFall", "Whether a significant fall writes a fall imprint.", true);
        WRITE_BUILD = SpecValues.bool(builder, "writeBuild", "Whether placing or breaking a block writes a build or redstone imprint.", true);
        FALL_DISTANCE_MIN = SpecValues.decimal(builder, "fallDistanceMin", "Minimum fall distance, in blocks, before a fall imprint is written.", 4.0D, 1.0D, 40.0D);
        EXTRACTION_DURABILITY_COST = SpecValues.integer(builder, "extractionDurabilityCost", "Durability the extraction needle loses on a successful extract.", 2, 0, 32);
        EXTRACTION_COOLDOWN_TICKS = SpecValues.integer(builder, "extractionCooldownTicks", "Ticks before the extraction needle can extract again. 0 disables the cooldown.", 20, 0, 200);
        FAILURE_PRESSURE_SPIKE = SpecValues.integer(builder, "failurePressureSpike", "Instability added to the composition reel's chunk when a formula fails. A moment replicant is asked only if the chunk is then overloaded or fractured.", 18, 0, 100);
        INSTABILITY_DECAY = SpecValues.integer(builder, "instabilityDecay", "Instability removed from a player's chunk on each decay pulse. 0 disables cooling. Loud imprints stay until extracted.", 1, 0, 20);
        INSTABILITY_DECAY_TICKS = SpecValues.integer(builder, "instabilityDecayTicks", "Ticks between instability and quiet-imprint pulses while a player is in the chunk. 0 disables the pulse.", 200, 0, 20_000);
        QUIET_FADE_TICKS = SpecValues.integer(builder, "quietFadeTicks", "Game ticks before the oldest build, redstone, or path imprint in a visited chunk can fade. One fades per pulse, and one may fade when the chunk loads. 0 disables the fade. Deaths, explosions, falls, fire, silence, and player imprints stay until extracted.", 6000, 0, 72_000);
        VEIN_SHIMMER_TICKS = SpecValues.integer(builder, "veinShimmerTicks", "Ticks between vein particle repeats while a held lens snapshot has not changed. 0 repeats only when the snapshot is new. A changed chunk still shimmers immediately.", 40, 0, 200);
        ALLOW_AMBIENT_PRESSURE = SpecValues.bool(builder, "allowAmbientPressure", "Whether the server may send full nearby pressure snapshots to a player who is not holding a chronicle lens. Without it such a player gets only the band-only snapshot (overloaded and fracture chunks) used for fracture feel. Vein marks stay lens-only. The client visuals.ambientWithoutLens toggle only draws the shimmer; it cannot grant the snapshot by itself.", false);
        SATURATED_THRESHOLD = SpecValues.integer(builder, "saturatedThreshold", "Pressure at which a chunk becomes saturated. Multiplied by recollectionStormThreshold and capped at pressureSoftCap.", 20, 1, 10_000);
        OVERLOADED_THRESHOLD = SpecValues.integer(builder, "overloadedThreshold", "Pressure at which a chunk becomes overloaded. Multiplied by recollectionStormThreshold and capped at pressureSoftCap.", 50, 1, 10_000);
        FRACTURE_THRESHOLD = SpecValues.integer(builder, "fractureThreshold", "Pressure at which a chunk fractures. Multiplied by recollectionStormThreshold and capped at pressureSoftCap. Fracture is logged and can spawn a moment replicant.", 80, 1, 10_000);
        MUTE_RADIUS_CHUNKS = SpecValues.integer(builder, "muteRadiusChunks", "Chebyshev radius, in chunks, of loaded chunks where a mute stone blocks imprint writes. 0 is the stone's own chunk.", 0, 0, 2);
        CATALOG_ENABLED = SpecValues.bool(builder, "catalogEnabled", "Whether a catalog fragment opens the discovery catalog.", true);
        DISCOVERY_HINTS = SpecValues.bool(builder, "discoveryHints", "Whether the catalog and reel may show how many stable patterns are still unread. They never list an unread pattern.", true);
        builder.pop();

        SpecValues.section(builder, "mobs", "Spawn gates, damage, and the archivist steal cooldown. Eggs and /mnemolith spawn ignore the weight and pressure gates.");
        ECHO_STRIDER_ENABLED = SpecValues.bool(builder, "echoStriderEnabled", "Whether echo striders may spawn from pressure and whether their AI runs.", true);
        ARCHIVIST_ENABLED = SpecValues.bool(builder, "archivistEnabled", "Whether archivists may spawn from pressure and whether they steal slips.", true);
        MOMENT_REPLICANT_ENABLED = SpecValues.bool(builder, "momentReplicantEnabled", "Whether moment replicants may spawn from fracture, an overloaded composition failure, or natural pressure.", true);
        ECHO_STRIDER_DAMAGE = SpecValues.decimal(builder, "echoStriderDamage", "Attack damage of an echo strider charge.", 4.0D, 0.0D, 40.0D);
        ARCHIVIST_DAMAGE = SpecValues.decimal(builder, "archivistDamage", "Attack damage of an archivist. Theft is the threat; this is only a shove.", 2.0D, 0.0D, 40.0D);
        REPLICANT_DAMAGE = SpecValues.decimal(builder, "replicantDamage", "Attack damage when a moment replicant copies a melee hit.", 5.0D, 0.0D, 40.0D);
        ARCHIVIST_STEAL_COOLDOWN = SpecValues.integer(builder, "archivistStealCooldown", "Ticks an archivist waits after a successful theft before it can steal again.", 300, 20, 20_000);
        ECHO_STRIDER_SPAWN_WEIGHT = SpecValues.integer(builder, "echoStriderSpawnWeight", "Chance, out of 100, that a natural echo strider spawn attempt is kept. 0 disables natural spawns.", 35, 0, 100);
        ARCHIVIST_SPAWN_WEIGHT = SpecValues.integer(builder, "archivistSpawnWeight", "Chance, out of 100, that a natural archivist spawn attempt is kept. 0 disables natural spawns.", 25, 0, 100);
        REPLICANT_SPAWN_WEIGHT = SpecValues.integer(builder, "replicantSpawnWeight", "Chance, out of 100, that a natural moment replicant spawn attempt is kept. 0 disables natural spawns.", 12, 0, 100);
        ECHO_STRIDER_MIN_PRESSURE = SpecValues.integer(builder, "echoStriderMinPressure", "Minimum cached pressure before an echo strider can spawn naturally. Defaults to the saturated band.", 20, 0, 10_000);
        ARCHIVIST_MIN_PRESSURE = SpecValues.integer(builder, "archivistMinPressure", "Minimum cached pressure before an archivist can spawn naturally. Defaults to the overloaded band.", 50, 0, 10_000);
        REPLICANT_MIN_PRESSURE = SpecValues.integer(builder, "replicantMinPressure", "Minimum cached pressure before a moment replicant can spawn naturally. Defaults to the fracture band.", 80, 0, 10_000);
        SENSOR_INTERVAL = SpecValues.integer(builder, "sensorInterval", "Ticks between archivist resonator scans, flee pressure scans, and idle strider repaths. A charge still aims every tick. 1 checks every tick.", 10, 1, 100);
        builder.pop();

        SpecValues.section(builder, "echo", "Echoes: self-recordings that replay as a helper body you can possess.");
        ECHOES_ENABLED = SpecValues.bool(builder, "echoesEnabled", "Whether echo slips record, recordings spawn echoes, and the lens can possess an echo.", true);
        ECHO_RECORD_SECONDS = SpecValues.integer(builder, "echoRecordSeconds", "Length, in seconds, of one self-recording.", 25, 5, 60);
        ECHO_MAX_PER_PLAYER = SpecValues.integer(builder, "echoMaxPerPlayer", "Echoes one player may own at once. Stage 1 is tuned for 1.", 1, 1, 4);
        ECHO_ACTIVATE_RANGE = SpecValues.integer(builder, "echoActivateRange", "Furthest distance, in blocks, from the recording's start at which a recording can be activated.", 48, 8, 256);
        ECHO_POSSESS_RANGE = SpecValues.integer(builder, "echoPossessRange", "Furthest distance, in blocks, at which the lens can possess your echo.", 32, 4, 64);
        ECHO_MAX_HEALTH = SpecValues.decimal(builder, "echoMaxHealth", "Maximum health of an echo body.", 20.0D, 1.0D, 100.0D);
        ECHO_DEATH_PRESSURE_SPIKE = SpecValues.integer(builder, "echoDeathPressureSpike", "Instability added to the chunk where an echo body dies.", 24, 0, 200);
        ECHO_SHELL_AGGRO_RADIUS = SpecValues.integer(builder, "echoShellAggroRadius", "Radius, in blocks, in which idle hostile mobs notice the empty shell you leave while possessing. 0 turns it off.", 12, 0, 32);
        ECHO_MINE_RADIUS = SpecValues.integer(builder, "echoMineRadius", "Default search radius, in blocks, of a mining job around its work anchor.", 16, 2, 32);
        ECHO_MINE_MAX_RADIUS = SpecValues.integer(builder, "echoMineMaxRadius", "Largest mining radius a player can pick on the echo screen.", 32, 2, 32);
        ECHO_TUNNEL_MAX = SpecValues.integer(builder, "echoTunnelMax", "Most blocks (natural stone, deepslate, dirt) an echo may dig to reach one enclosed target. 0 turns tunnelling off.", 12, 0, 64);
        ECHO_DEPOSIT_FREE_SLOTS = SpecValues.integer(builder, "echoDepositFreeSlots", "A mining echo walks to its chest when this many main slots or fewer are still empty.", 1, 0, 27);
        ECHO_BUILD_CLEARS_TERRAIN = SpecValues.bool(builder, "echoBuildClearsTerrain", "Whether a building echo may break natural terrain (stone, dirt, sand, gravel, plants) that stands where the blueprint needs a block. Other blocks are never overwritten.", false);
        ECHO_SCAN_BUDGET = SpecValues.integer(builder, "echoScanBudget", "Block positions a mining echo may inspect per tick while searching for targets.", 4096, 256, 65536);
        ECHO_PATH_BUDGET = SpecValues.integer(builder, "echoPathBudget", "Path nodes an echo may expand per tick. A search gives up after 16 times this many.", 400, 50, 4000);
        ECHO_MOB_AGGRO = SpecValues.bool(builder, "echoMobAggro", "Whether hostile mobs (not creepers, neutral mobs or memory mobs) may pick a working echo as a target. The echo never fights back: it flees and resumes later.", true);
        ECHO_FLEE_DISTANCE = SpecValues.integer(builder, "echoFleeDistance", "How far, in blocks, an attacked echo runs from its attacker before it waits.", 8, 3, 24);
        ECHO_FLEE_SAFE_TICKS = SpecValues.integer(builder, "echoFleeSafeTicks", "Ticks without a hit, and without a hostile mob targeting it nearby, before an attacked echo goes back to work.", 100, 20, 1200);
        ECHO_ARCHIVIST_STEAL = SpecValues.bool(builder, "echoArchivistSteal", "Whether an archivist may steal one non-tool stack from a working echo. It keeps the loot until it is killed, and then always drops it.", true);
        ECHO_ARCHIVIST_STEAL_MAX = SpecValues.integer(builder, "echoArchivistStealMax", "Most items an archivist takes from one echo stack.", 8, 1, 64);
        ECHO_REPLICANT_MIMIC_TICKS = SpecValues.integer(builder, "echoReplicantMimicTicks", "How long, in ticks, a moment replicant mimics a working echo's job. 0 turns the mimic off.", 200, 0, 1200);
        ECHO_REPLICANT_UNDO_MAX = SpecValues.integer(builder, "echoReplicantUndoMax", "Most blocks a mimicking replicant pulls back from one build (the item goes back to the echo), or stumbles a miner or farmer.", 3, 0, 16);
        ECHO_STRIDER_SHADOW = SpecValues.bool(builder, "echoStriderShadow", "Whether echo striders shadow a working echo like a recorded path, and charge it when its chunk is overloaded.", true);
        ECHO_MAX_PER_PLAYER_CAP = SpecValues.integer(builder, "echoMaxPerPlayerCap", "Most echoes one player may own with chorus slips. Each chorus slip adds one above echoMaxPerPlayer, up to this cap.", 3, 1, 8);
        ECHO_RECORD_BONUS_SECONDS = SpecValues.integer(builder, "echoRecordBonusSeconds", "Seconds each long take slip adds to a recording (a recording never exceeds 60 seconds).", 10, 0, 30);
        ECHO_RECORD_UPGRADE_MAX = SpecValues.integer(builder, "echoRecordUpgradeMax", "How many long take slips one player may absorb.", 2, 0, 5);
        ECHO_STURDY_HEALTH_BONUS = SpecValues.decimal(builder, "echoSturdyHealthBonus", "Max health each sturdy body slip adds to the player's echoes.", 10.0D, 0.0D, 50.0D);
        ECHO_STURDY_UPGRADE_MAX = SpecValues.integer(builder, "echoSturdyUpgradeMax", "How many sturdy body slips one player may absorb.", 2, 0, 5);
        ECHO_FARM_MAX_RADIUS = SpecValues.integer(builder, "echoFarmMaxRadius", "Largest radius a farming echo tends around its work point (the job radius is capped to this). Three blocks up and down are scanned too.", 12, 2, 32);
        ECHO_FARM_POLL_TICKS = SpecValues.integer(builder, "echoFarmPollTicks", "Ticks a farming echo waits between two looks at its field when nothing is ripe.", 100, 20, 1200);
        ECHO_WORK_IMPRINT_EVERY = SpecValues.integer(builder, "echoWorkImprintEvery", "Blocks an echo mines, places or harvests in one chunk before the work leaves a build imprint there (by the owner). 0 turns work imprints off.", 20, 0, 1000);
        ECHO_WORK_INSTABILITY = SpecValues.integer(builder, "echoWorkInstability", "Instability added with each work imprint (on top of the imprint itself).", 3, 0, 50);
        ECHO_MISFIRE_CHANCE = SpecValues.decimal(builder, "echoMisfireChance", "Chance per action that an echo working in an overloaded chunk misfires: a skipped or wrong block (taken back and fixed later), never lost or duplicated items.", 0.15D, 0.0D, 1.0D);
        ECHO_FRACTURE_STOPS = SpecValues.bool(builder, "echoFractureStops", "Whether an echo stops working in a chunk that reached the fracture band.", true);
        ECHO_FOLLOW_LOST_DISTANCE = SpecValues.integer(builder, "echoFollowLostDistance", "Blocks between an echo told to follow and its owner after which it gives up and stays.", 48, 8, 128);
        builder.pop();

        SPEC = builder.build();
    }

    private CommonConfig() {}
}
