package com.mnemolith.config;

import net.neoforged.neoforge.common.ModConfigSpec;

/**
 * Common config ({@code mnemolith-common.toml}). Loaded on the physical client and the dedicated server.
 */
public final class CommonConfig {
    public static final ModConfigSpec.DoubleValue RECOLLECTION_STORM_THRESHOLD;
    public static final ModConfigSpec.IntValue PRESSURE_SOFT_CAP;
    public static final ModConfigSpec.IntValue IMPRINT_NODE_WEIGHT;
    public static final ModConfigSpec.DoubleValue STORM_ATTEMPT_CHANCE;
    public static final ModConfigSpec.BooleanValue STRUCTURES_ENABLED;
    public static final ModConfigSpec.IntValue STRUCTURE_SPACING;
    public static final ModConfigSpec.BooleanValue COMPOSITION_ENABLED;
    public static final ModConfigSpec.IntValue MAX_IMPRINTS_PER_CHUNK;
    public static final ModConfigSpec.BooleanValue WRITE_IMPRINTS;
    public static final ModConfigSpec.IntValue WRITE_DEBOUNCE_TICKS;
    public static final ModConfigSpec.BooleanValue WRITE_DEATH;
    public static final ModConfigSpec.BooleanValue WRITE_EXPLOSION;
    public static final ModConfigSpec.BooleanValue WRITE_FALL;
    public static final ModConfigSpec.BooleanValue WRITE_BUILD;
    public static final ModConfigSpec.DoubleValue FALL_DISTANCE_MIN;
    public static final ModConfigSpec.IntValue EXTRACTION_DURABILITY_COST;
    public static final ModConfigSpec.IntValue EXTRACTION_COOLDOWN_TICKS;
    public static final ModConfigSpec.IntValue FAILURE_PRESSURE_SPIKE;
    public static final ModConfigSpec.IntValue INSTABILITY_DECAY;
    public static final ModConfigSpec.IntValue INSTABILITY_DECAY_TICKS;
    public static final ModConfigSpec.IntValue QUIET_FADE_TICKS;
    public static final ModConfigSpec.IntValue VEIN_SHIMMER_TICKS;
    public static final ModConfigSpec.BooleanValue ALLOW_AMBIENT_PRESSURE;
    public static final ModConfigSpec.IntValue SATURATED_THRESHOLD;
    public static final ModConfigSpec.IntValue OVERLOADED_THRESHOLD;
    public static final ModConfigSpec.IntValue FRACTURE_THRESHOLD;
    public static final ModConfigSpec.IntValue MUTE_RADIUS_CHUNKS;
    public static final ModConfigSpec.BooleanValue CATALOG_ENABLED;
    public static final ModConfigSpec.BooleanValue DISCOVERY_HINTS;
    public static final ModConfigSpec.BooleanValue ECHO_STRIDER_ENABLED;
    public static final ModConfigSpec.BooleanValue ARCHIVIST_ENABLED;
    public static final ModConfigSpec.BooleanValue MOMENT_REPLICANT_ENABLED;
    public static final ModConfigSpec.DoubleValue ECHO_STRIDER_DAMAGE;
    public static final ModConfigSpec.DoubleValue ARCHIVIST_DAMAGE;
    public static final ModConfigSpec.DoubleValue REPLICANT_DAMAGE;
    public static final ModConfigSpec.IntValue ARCHIVIST_STEAL_COOLDOWN;
    public static final ModConfigSpec.IntValue ECHO_STRIDER_SPAWN_WEIGHT;
    public static final ModConfigSpec.IntValue ARCHIVIST_SPAWN_WEIGHT;
    public static final ModConfigSpec.IntValue REPLICANT_SPAWN_WEIGHT;
    public static final ModConfigSpec.IntValue ECHO_STRIDER_MIN_PRESSURE;
    public static final ModConfigSpec.IntValue ARCHIVIST_MIN_PRESSURE;
    public static final ModConfigSpec.IntValue REPLICANT_MIN_PRESSURE;
    public static final ModConfigSpec.IntValue SENSOR_INTERVAL;
    public static final ModConfigSpec.BooleanValue ARCHIVAL_VEINS_ENABLED;
    public static final ModConfigSpec.IntValue ARCHIVAL_VEIN_CHANCE;
    public static final ModConfigSpec.IntValue ARCHIVAL_VEIN_MIN_Y;
    public static final ModConfigSpec.IntValue ARCHIVAL_VEIN_MAX_Y;
    public static final ModConfigSpec.IntValue ARCHIVAL_VEIN_SIZE;
    public static final ModConfigSpec.IntValue ARCHIVAL_BLEED;
    public static final ModConfigSpec.IntValue ARCHIVAL_BLEED_CAP;
    public static final ModConfigSpec.BooleanValue MUTE_POCKETS_ENABLED;
    public static final ModConfigSpec.IntValue MUTE_POCKET_CHANCE;
    public static final ModConfigSpec.IntValue MUTE_POCKET_MIN_Y;
    public static final ModConfigSpec.IntValue MUTE_POCKET_MAX_Y;
    public static final ModConfigSpec.BooleanValue OBSERVATORY_ENABLED;
    public static final ModConfigSpec.BooleanValue ARCHIVIST_OBSERVATORY_BIAS;
    public static final ModConfigSpec.BooleanValue STRIDER_PATH_BIAS;
    public static final ModConfigSpec.BooleanValue ECHOES_ENABLED;
    public static final ModConfigSpec.IntValue ECHO_RECORD_SECONDS;
    public static final ModConfigSpec.IntValue ECHO_MAX_PER_PLAYER;
    public static final ModConfigSpec.IntValue ECHO_ACTIVATE_RANGE;
    public static final ModConfigSpec.IntValue ECHO_POSSESS_RANGE;
    public static final ModConfigSpec.DoubleValue ECHO_MAX_HEALTH;
    public static final ModConfigSpec.IntValue ECHO_DEATH_PRESSURE_SPIKE;
    public static final ModConfigSpec.IntValue ECHO_SHELL_AGGRO_RADIUS;
    public static final ModConfigSpec.IntValue ECHO_MINE_RADIUS;
    public static final ModConfigSpec.IntValue ECHO_MINE_MAX_RADIUS;
    public static final ModConfigSpec.IntValue ECHO_TUNNEL_MAX;
    public static final ModConfigSpec.IntValue ECHO_DEPOSIT_FREE_SLOTS;
    public static final ModConfigSpec.BooleanValue ECHO_BUILD_CLEARS_TERRAIN;
    public static final ModConfigSpec.IntValue ECHO_SCAN_BUDGET;
    public static final ModConfigSpec.IntValue ECHO_PATH_BUDGET;
    public static final ModConfigSpec.BooleanValue ECHO_MOB_AGGRO;
    public static final ModConfigSpec.IntValue ECHO_FLEE_DISTANCE;
    public static final ModConfigSpec.IntValue ECHO_FLEE_SAFE_TICKS;
    public static final ModConfigSpec.BooleanValue ECHO_ARCHIVIST_STEAL;
    public static final ModConfigSpec.IntValue ECHO_ARCHIVIST_STEAL_MAX;
    public static final ModConfigSpec.IntValue ECHO_REPLICANT_MIMIC_TICKS;
    public static final ModConfigSpec.IntValue ECHO_REPLICANT_UNDO_MAX;
    public static final ModConfigSpec.BooleanValue ECHO_STRIDER_SHADOW;
    public static final ModConfigSpec.IntValue ECHO_MAX_PER_PLAYER_CAP;
    public static final ModConfigSpec.IntValue ECHO_RECORD_BONUS_SECONDS;
    public static final ModConfigSpec.IntValue ECHO_RECORD_UPGRADE_MAX;
    public static final ModConfigSpec.DoubleValue ECHO_STURDY_HEALTH_BONUS;
    public static final ModConfigSpec.IntValue ECHO_STURDY_UPGRADE_MAX;
    public static final ModConfigSpec.IntValue ECHO_FARM_MAX_RADIUS;
    public static final ModConfigSpec.IntValue ECHO_FARM_POLL_TICKS;
    public static final ModConfigSpec.IntValue ECHO_WORK_IMPRINT_EVERY;
    public static final ModConfigSpec.IntValue ECHO_WORK_INSTABILITY;
    public static final ModConfigSpec.DoubleValue ECHO_MISFIRE_CHANCE;
    public static final ModConfigSpec.BooleanValue ECHO_FRACTURE_STOPS;
    public static final ModConfigSpec.IntValue ECHO_FOLLOW_LOST_DISTANCE;
    public static final ModConfigSpec.BooleanValue ECHO_GRAFTS_ENABLED;
    public static final ModConfigSpec.DoubleValue ECHO_GRAFT_CHARGE_SCALE;
    public static final ModConfigSpec.IntValue ECHO_GRAFT_AURA_RADIUS;
    public static final ModConfigSpec.BooleanValue RESIDUES_ENABLED;
    public static final ModConfigSpec.DoubleValue RESIDUE_FORM_CHANCE;
    public static final ModConfigSpec.DoubleValue RESIDUE_FRACTURE_FORM_CHANCE;
    public static final ModConfigSpec.IntValue RESIDUE_FESTER_SECONDS;
    public static final ModConfigSpec.IntValue RESIDUE_MAX_NEARBY;
    public static final ModConfigSpec.DoubleValue RESIDUE_LASH_RADIUS;
    public static final ModConfigSpec.BooleanValue RESIDUE_ACTS_OUT;
    public static final ModConfigSpec.BooleanValue RELAY_ENABLED;
    public static final ModConfigSpec.IntValue RELAY_LINK_RANGE;
    public static final ModConfigSpec.IntValue RELAY_HOP_COOLDOWN_SECONDS;
    public static final ModConfigSpec.BooleanValue RELAY_MIRROR;
    public static final ModConfigSpec.BooleanValue VAULTS_ENABLED;
    public static final ModConfigSpec.IntValue VAULT_CAPACITY;
    public static final ModConfigSpec.IntValue VAULT_DRAW_SECONDS;
    public static final ModConfigSpec.DoubleValue VAULT_BLEED;
    public static final ModConfigSpec.IntValue VAULT_LEAK_SECONDS;
    public static final ModConfigSpec.BooleanValue RECALL_ENABLED;
    public static final ModConfigSpec.IntValue RECALL_MAX_GESTURES;
    public static final ModConfigSpec.IntValue RECALL_MIN_AGE;
    public static final ModConfigSpec.IntValue RECALL_MAX_AGE;
    public static final ModConfigSpec.IntValue RECALL_COOLDOWN;
    public static final ModConfigSpec.DoubleValue RECALL_CHANCE;
    public static final ModConfigSpec.DoubleValue RECALL_LOCAL_CHANCE;
    public static final ModConfigSpec.DoubleValue RECALL_DISTORTION_CHANCE;
    public static final ModConfigSpec.BooleanValue RECALL_RECORD_ATTACKS;
    public static final ModConfigSpec.BooleanValue RECALL_RECORD_PLACES;
    public static final ModConfigSpec.BooleanValue RECALL_RECORD_USES;
    public static final ModConfigSpec.BooleanValue RECALL_RECORD_FALLS;
    public static final ModConfigSpec.IntValue RECALL_IDLE_TICKS;
    public static final ModConfigSpec.IntValue RECALL_MATCH_TICKS;
    public static final ModConfigSpec.IntValue RECALL_VANISH_TICKS;
    public static final ModConfigSpec.IntValue RECALL_LOCAL_RADIUS;
    public static final ModConfigSpec.BooleanValue RECALL_SKIP_CREATIVE;
    public static final ModConfigSpec.BooleanValue RECALL_SKIP_STORM;
    public static final ModConfigSpec.BooleanValue INVESTIGATE_ENABLED;
    public static final ModConfigSpec.IntValue INVESTIGATE_MAX_ANCHORS;
    public static final ModConfigSpec.IntValue INVESTIGATE_MAX_AGE;
    public static final ModConfigSpec.IntValue INVESTIGATE_READ_TICKS;
    public static final ModConfigSpec.IntValue INVESTIGATE_READ_RANGE;
    public static final ModConfigSpec.IntValue INVESTIGATE_TRACE_RADIUS;
    public static final ModConfigSpec.IntValue INVESTIGATE_LINGER;
    public static final ModConfigSpec.BooleanValue INVESTIGATE_RECORD_DEATH;
    public static final ModConfigSpec.BooleanValue INVESTIGATE_RECORD_MUTE;
    public static final ModConfigSpec.BooleanValue INVESTIGATE_RECORD_BLANK;
    public static final ModConfigSpec.BooleanValue INVESTIGATE_RECORD_ECHO;
    public static final ModConfigSpec.BooleanValue INVESTIGATE_RECORD_FRACTURE;
    public static final ModConfigSpec.BooleanValue INVESTIGATE_RECORD_LOUD;
    public static final ModConfigSpec.BooleanValue INVESTIGATE_RECORD_TRACES;
    public static final ModConfigSpec.BooleanValue USE_ENABLED;
    public static final ModConfigSpec.IntValue USE_MIN_ANCHORS;
    public static final ModConfigSpec.DoubleValue USE_LIE_CHANCE;
    public static final ModConfigSpec.DoubleValue USE_LIE_AFTER_LEAVE;
    public static final ModConfigSpec.IntValue USE_LIE_OFFSET;
    public static final ModConfigSpec.IntValue USE_GUIDE_RANGE;
    public static final ModConfigSpec.IntValue USE_GUIDE_COOLDOWN;
    public static final ModConfigSpec.IntValue USE_CONDENSE_RANGE;
    public static final ModConfigSpec.IntValue USE_WITNESS_RANGE;
    public static final ModConfigSpec.IntValue USE_LEAVE_RANGE;
    public static final ModConfigSpec.IntValue USE_STORE_RANGE;
    public static final ModConfigSpec.IntValue USE_RESIDUE_STRENGTH;
    public static final ModConfigSpec.BooleanValue INTERVENE_ENABLED;
    public static final ModConfigSpec.IntValue INTERVENE_RANGE;
    public static final ModConfigSpec.BooleanValue INTERVENE_ONCE;
    public static final ModConfigSpec.IntValue INTERVENE_INSTABILITY;
    public static final ModConfigSpec.DoubleValue GRAVE_DAMAGE_MULT;
    public static final ModConfigSpec.DoubleValue GRAVE_SPEED_PENALTY;
    public static final ModConfigSpec.DoubleValue HUSH_STEP_BONUS;
    public static final ModConfigSpec.IntValue RECALL_BLADE_COOLDOWN;
    public static final ModConfigSpec.IntValue SCAR_BRAND_COOLDOWN;
    public static final ModConfigSpec.IntValue STALKER_SPAWN_WEIGHT;
    public static final ModConfigSpec.IntValue STALKER_MIN_PRESSURE;
    public static final ModConfigSpec.BooleanValue SLEEP_CONSOLIDATION;
    public static final ModConfigSpec.IntValue SLEEP_COOL_AMOUNT;
    public static final ModConfigSpec.IntValue SLEEP_FADE_PASSES;
    public static final ModConfigSpec.BooleanValue SLEEP_NIGHTMARE;
    public static final ModConfigSpec SPEC;

    static {
        ModConfigSpec.Builder builder = new ModConfigSpec.Builder();

        SpecValues.section(builder, "difficulty", "Thresholds that decide when recollection becomes dangerous.");
        RECOLLECTION_STORM_THRESHOLD = SpecValues.decimal(builder, "recollectionStormThreshold", "Multiplier on the saturated, overloaded, and fracture thresholds. Each scaled threshold is capped at pressureSoftCap, so fracture stays reachable. Recollection storms can only gather in a fractured chunk, so this also sets how loud a place must get before a storm is possible: higher means later and rarer storms.", 1.0D, 0.1D, 10.0D);
        PRESSURE_SOFT_CAP = SpecValues.integer(builder, "pressureSoftCap", "Soft cap for memory pressure accumulated from imprints in loaded chunks.", 100, 1, 10_000);
        builder.pop();

        SpecValues.section(builder, "spawnRates", "How often recollection storms are attempted, and a reserved imprint node weight that worldgen does not use yet.");
        IMPRINT_NODE_WEIGHT = SpecValues.integer(builder, "imprintNodeWeight", "Reserved, not used yet: no worldgen feature places imprint-bearing nodes. Relative weight of such nodes when structures are placed.", 4, 0, 100);
        STORM_ATTEMPT_CHANCE = SpecValues.decimal(builder, "stormAttemptChance", "Chance, from 0.0 to 1.0, rolled once a second for each player standing in a fractured chunk, that a recollection storm starts gathering there (if allowRecollectionStorms, maxStormsPerDimension, mute stones and scar wards allow it). 0.02 means a storm usually gathers within a minute or two. 0 turns natural storms off; a freed residual shard can still call one.", 0.02D, 0.0D, 1.0D);
        builder.pop();

        SpecValues.section(builder, "worldGen", "Structure placement defaults. Changing these takes effect the next time a world loads.");
        STRUCTURES_ENABLED = SpecValues.boolRestart(builder, "structuresEnabled", "Whether the chronicle observatory may generate. Veins and mute pockets have their own toggles.", true);
        STRUCTURE_SPACING = SpecValues.integerRestart(builder, "structureSpacing", "Documented spacing, in chunks, of the chronicle observatory. The structure set json uses 32 and a separation of 12. Editing this number does not move structures.", 32, 8, 256);
        ARCHIVAL_VEINS_ENABLED = SpecValues.bool(builder, "archivalVeinsEnabled", "Whether archival veins may generate. The biome modifier uses #minecraft:is_overworld. The Y range keeps them underground.", true);
        ARCHIVAL_VEIN_CHANCE = SpecValues.integer(builder, "archivalVeinChance", "Chance, out of 100, that a chunk attempts an archival vein.", 8, 0, 100);
        ARCHIVAL_VEIN_MIN_Y = SpecValues.integer(builder, "archivalVeinMinY", "Lowest Y of an archival vein.", -48, -64, 320);
        ARCHIVAL_VEIN_MAX_Y = SpecValues.integer(builder, "archivalVeinMaxY", "Highest Y of an archival vein.", 32, -64, 320);
        ARCHIVAL_VEIN_SIZE = SpecValues.integer(builder, "archivalVeinSize", "Length, in blocks, of one archival vein.", 7, 3, 16);
        ARCHIVAL_BLEED = SpecValues.integer(builder, "archivalBleed", "Pressure added per archival stratum block when the chunk's pressure is scored.", 1, 0, 20);
        ARCHIVAL_BLEED_CAP = SpecValues.integer(builder, "archivalBleedCap", "Most stratum blocks that contribute pressure in one chunk.", 6, 0, 64);
        MUTE_POCKETS_ENABLED = SpecValues.bool(builder, "mutePocketsEnabled", "Whether mute pockets may generate. Placed mute stone uses the same write suppression as a crafted mute stone.", true);
        MUTE_POCKET_CHANCE = SpecValues.integer(builder, "mutePocketChance", "Chance, out of 100, that a chunk attempts a mute pocket.", 4, 0, 100);
        MUTE_POCKET_MIN_Y = SpecValues.integer(builder, "mutePocketMinY", "Lowest Y of a mute pocket.", -32, -64, 320);
        MUTE_POCKET_MAX_Y = SpecValues.integer(builder, "mutePocketMaxY", "Highest Y of a mute pocket.", 48, -64, 320);
        OBSERVATORY_ENABLED = SpecValues.boolRestart(builder, "observatoryEnabled", "Whether chronicle observatories may generate. Also requires structuresEnabled.", true);
        ARCHIVIST_OBSERVATORY_BIAS = SpecValues.bool(builder, "archivistObservatoryBias", "Whether an archivist's natural pressure gate is lower in and near an observatory chunk.", true);
        STRIDER_PATH_BIAS = SpecValues.bool(builder, "striderPathBias", "Whether an echo strider's natural pressure gate is lower in a chunk that already holds a path imprint.", true);
        builder.pop();

        SpecValues.section(builder, "gameplay", "Player-facing memory rules for writing, extraction, and composition.");
        COMPOSITION_ENABLED = SpecValues.bool(builder, "compositionEnabled", "Whether players may compose extracted imprints.", true);
        MAX_IMPRINTS_PER_CHUNK = SpecValues.integer(builder, "maxImprintsPerChunk", "Maximum imprints stored on a single chunk. Lowest intensity is dropped first.", 8, 1, 64);
        WRITE_IMPRINTS = SpecValues.bool(builder, "writeImprints", "Whether world events write imprints.", true);
        WRITE_DEBOUNCE_TICKS = SpecValues.integer(builder, "writeDebounceTicks", "Ticks that must pass before another build or redstone imprint can be written in the same chunk.", 80, 1, 200);
        WRITE_DEATH = SpecValues.bool(builder, "writeDeath", "Whether a death writes a death imprint.", true);
        WRITE_EXPLOSION = SpecValues.bool(builder, "writeExplosion", "Whether an explosion writes an explosion imprint.", true);
        WRITE_FALL = SpecValues.bool(builder, "writeFall", "Whether a significant fall writes a fall imprint.", true);
        WRITE_BUILD = SpecValues.bool(builder, "writeBuild", "Whether placing or breaking a block writes a build or redstone imprint.", true);
        FALL_DISTANCE_MIN = SpecValues.decimal(builder, "fallDistanceMin", "Minimum fall distance, in blocks, before a fall imprint is written.", 4.0D, 1.0D, 40.0D);
        EXTRACTION_DURABILITY_COST = SpecValues.integer(builder, "extractionDurabilityCost", "Durability the extraction needle loses on a successful extract.", 2, 0, 32);
        EXTRACTION_COOLDOWN_TICKS = SpecValues.integer(builder, "extractionCooldownTicks", "Ticks before the extraction needle can extract again. 0 disables the cooldown.", 20, 0, 200);
        FAILURE_PRESSURE_SPIKE = SpecValues.integer(builder, "failurePressureSpike", "Instability added to the composition reel's chunk when a formula fails. A moment replicant is asked only if the chunk is then overloaded or fractured.", 18, 0, 100);
        INSTABILITY_DECAY = SpecValues.integer(builder, "instabilityDecay", "Instability removed from a player's chunk on each decay pulse. 0 disables cooling. Loud imprints stay until extracted.", 1, 0, 20);
        INSTABILITY_DECAY_TICKS = SpecValues.integer(builder, "instabilityDecayTicks", "Ticks between instability and quiet-imprint pulses while a player is in the chunk. 0 disables the pulse.", 200, 0, 20_000);
        QUIET_FADE_TICKS = SpecValues.integer(builder, "quietFadeTicks", "Game ticks before the oldest build, redstone, or path imprint in a visited chunk can fade. One fades per pulse, and one may fade when the chunk loads. 0 disables the fade. Deaths, explosions, falls, fire, silence, and player imprints stay until extracted.", 6000, 0, 72_000);
        VEIN_SHIMMER_TICKS = SpecValues.integer(builder, "veinShimmerTicks", "Ticks between vein particle repeats while a held lens snapshot has not changed. 0 repeats only when the snapshot is new. A changed chunk still shimmers immediately.", 40, 0, 200);
        ALLOW_AMBIENT_PRESSURE = SpecValues.bool(builder, "allowAmbientPressure", "Whether the server may send full nearby pressure snapshots to a player who is not holding a chronicle lens. Without it such a player gets only the band-only snapshot (overloaded and fracture chunks) used for fracture feel. Vein marks stay lens-only. The client visuals.ambientWithoutLens toggle only decides whether the client asks and draws; it cannot grant the snapshot by itself.", false);
        SATURATED_THRESHOLD = SpecValues.integer(builder, "saturatedThreshold", "Pressure at which a chunk becomes saturated. Multiplied by recollectionStormThreshold and capped at pressureSoftCap.", 20, 1, 10_000);
        OVERLOADED_THRESHOLD = SpecValues.integer(builder, "overloadedThreshold", "Pressure at which a chunk becomes overloaded. Multiplied by recollectionStormThreshold and capped at pressureSoftCap.", 50, 1, 10_000);
        FRACTURE_THRESHOLD = SpecValues.integer(builder, "fractureThreshold", "Pressure at which a chunk fractures. Multiplied by recollectionStormThreshold and capped at pressureSoftCap. Fracture is logged, can spawn a moment replicant, and is where a recollection storm can gather.", 80, 1, 10_000);
        MUTE_RADIUS_CHUNKS = SpecValues.integer(builder, "muteRadiusChunks", "Chebyshev radius, in chunks, of loaded chunks where a mute stone blocks imprint writes. 0 is the stone's own chunk.", 0, 0, 2);
        CATALOG_ENABLED = SpecValues.bool(builder, "catalogEnabled", "Whether a catalog fragment opens the discovery catalog.", true);
        DISCOVERY_HINTS = SpecValues.bool(builder, "discoveryHints", "Whether the catalog and reel may show how many stable patterns are still unread. They never list an unread pattern.", true);
        builder.pop();

        SpecValues.section(builder, "mobs", "Spawn gates, damage, and the archivist steal cooldown. Eggs and /mnemolith spawn ignore the weight and pressure gates.");
        ECHO_STRIDER_ENABLED = SpecValues.bool(builder, "echoStriderEnabled", "Whether echo striders may spawn from pressure and whether their AI runs.", true);
        ARCHIVIST_ENABLED = SpecValues.bool(builder, "archivistEnabled", "Whether archivists may spawn from pressure and whether they steal slips.", true);
        MOMENT_REPLICANT_ENABLED = SpecValues.bool(builder, "momentReplicantEnabled", "Whether moment replicants may spawn from fracture, an overloaded composition failure, or natural pressure.", true);
        ECHO_STRIDER_DAMAGE = SpecValues.decimal(builder, "echoStriderDamage", "Attack damage of an echo strider charge.", 4.0D, 0.0D, 40.0D);
        ARCHIVIST_DAMAGE = SpecValues.decimal(builder, "archivistDamage", "Attack damage of an archivist. Theft is the threat; this is only a shove.", 2.0D, 0.0D, 40.0D);
        REPLICANT_DAMAGE = SpecValues.decimal(builder, "replicantDamage", "Attack damage when a moment replicant copies a melee hit.", 5.0D, 0.0D, 40.0D);
        ARCHIVIST_STEAL_COOLDOWN = SpecValues.integer(builder, "archivistStealCooldown", "Ticks an archivist waits after a successful theft before it can steal again.", 300, 20, 20_000);
        ECHO_STRIDER_SPAWN_WEIGHT = SpecValues.integer(builder, "echoStriderSpawnWeight", "Chance, out of 100, that a natural echo strider spawn attempt is kept. 0 disables natural spawns.", 35, 0, 100);
        ARCHIVIST_SPAWN_WEIGHT = SpecValues.integer(builder, "archivistSpawnWeight", "Chance, out of 100, that a natural archivist spawn attempt is kept. 0 disables natural spawns.", 25, 0, 100);
        REPLICANT_SPAWN_WEIGHT = SpecValues.integer(builder, "replicantSpawnWeight", "Chance, out of 100, that a natural moment replicant spawn attempt is kept. 0 disables natural spawns.", 12, 0, 100);
        ECHO_STRIDER_MIN_PRESSURE = SpecValues.integer(builder, "echoStriderMinPressure", "Minimum cached pressure before an echo strider can spawn naturally. Defaults to the saturated band.", 20, 0, 10_000);
        ARCHIVIST_MIN_PRESSURE = SpecValues.integer(builder, "archivistMinPressure", "Minimum cached pressure before an archivist can spawn naturally. Defaults to the overloaded band.", 50, 0, 10_000);
        REPLICANT_MIN_PRESSURE = SpecValues.integer(builder, "replicantMinPressure", "Minimum cached pressure before a moment replicant can spawn naturally. Defaults to the fracture band.", 80, 0, 10_000);
        SENSOR_INTERVAL = SpecValues.integer(builder, "sensorInterval", "Ticks between archivist resonator scans, flee pressure scans, and idle strider repaths. A charge still aims every tick. 1 checks every tick.", 10, 1, 100);
        builder.pop();

        SpecValues.section(builder, "echo", "Echoes: self-recordings that replay as a helper body you can possess.");
        ECHOES_ENABLED = SpecValues.bool(builder, "echoesEnabled", "Whether echo slips record, recordings spawn echoes, and the lens can possess an echo.", true);
        ECHO_RECORD_SECONDS = SpecValues.integer(builder, "echoRecordSeconds", "Length, in seconds, of one self-recording.", 25, 5, 60);
        ECHO_MAX_PER_PLAYER = SpecValues.integer(builder, "echoMaxPerPlayer", "Echoes one player may own before any chorus slip. Two, so a relay thread has both ends.", 2, 1, 4);
        ECHO_ACTIVATE_RANGE = SpecValues.integer(builder, "echoActivateRange", "Furthest distance, in blocks, from the recording's start at which a recording can be activated.", 48, 8, 256);
        ECHO_POSSESS_RANGE = SpecValues.integer(builder, "echoPossessRange", "Furthest distance, in blocks, at which the lens can possess your echo.", 32, 4, 64);
        ECHO_MAX_HEALTH = SpecValues.decimal(builder, "echoMaxHealth", "Maximum health of an echo body.", 20.0D, 1.0D, 100.0D);
        ECHO_DEATH_PRESSURE_SPIKE = SpecValues.integer(builder, "echoDeathPressureSpike", "Instability added to the chunk where an echo body dies.", 24, 0, 200);
        ECHO_SHELL_AGGRO_RADIUS = SpecValues.integer(builder, "echoShellAggroRadius", "Radius, in blocks, in which idle hostile mobs notice the empty shell you leave while possessing. 0 turns it off.", 12, 0, 32);
        ECHO_MINE_RADIUS = SpecValues.integer(builder, "echoMineRadius", "Default search radius, in blocks, of a mining job around its work anchor.", 16, 2, 32);
        ECHO_MINE_MAX_RADIUS = SpecValues.integer(builder, "echoMineMaxRadius", "Largest mining radius a player can pick on the echo screen.", 32, 2, 32);
        ECHO_TUNNEL_MAX = SpecValues.integer(builder, "echoTunnelMax", "Most blocks (natural stone, deepslate, dirt) an echo may dig to reach one enclosed target. 0 turns tunnelling off.", 12, 0, 64);
        ECHO_DEPOSIT_FREE_SLOTS = SpecValues.integer(builder, "echoDepositFreeSlots", "A mining echo walks to its chest when this many main slots or fewer are still empty.", 1, 0, 27);
        ECHO_BUILD_CLEARS_TERRAIN = SpecValues.bool(builder, "echoBuildClearsTerrain", "Whether a building echo may break natural terrain (stone, dirt, sand, gravel, plants) that stands where the blueprint needs a block. Other blocks are never overwritten.", false);
        ECHO_SCAN_BUDGET = SpecValues.integer(builder, "echoScanBudget", "Block positions a mining echo may inspect per tick while searching for targets.", 4096, 256, 65536);
        ECHO_PATH_BUDGET = SpecValues.integer(builder, "echoPathBudget", "Path nodes an echo may expand per tick. A search gives up after 16 times this many.", 400, 50, 4000);
        ECHO_MOB_AGGRO = SpecValues.bool(builder, "echoMobAggro", "Whether hostile mobs (not creepers, neutral mobs or memory mobs) may pick a working echo as a target. The echo never fights back: it flees and resumes later.", true);
        ECHO_FLEE_DISTANCE = SpecValues.integer(builder, "echoFleeDistance", "How far, in blocks, an attacked echo runs from its attacker before it waits.", 8, 3, 24);
        ECHO_FLEE_SAFE_TICKS = SpecValues.integer(builder, "echoFleeSafeTicks", "Ticks without a hit, and without a hostile mob targeting it nearby, before an attacked echo goes back to work.", 100, 20, 1200);
        ECHO_ARCHIVIST_STEAL = SpecValues.bool(builder, "echoArchivistSteal", "Whether an archivist may steal one non-tool stack from a working echo. It keeps the loot until it is killed, and then always drops it.", true);
        ECHO_ARCHIVIST_STEAL_MAX = SpecValues.integer(builder, "echoArchivistStealMax", "Most items an archivist takes from one echo stack.", 8, 1, 64);
        ECHO_REPLICANT_MIMIC_TICKS = SpecValues.integer(builder, "echoReplicantMimicTicks", "How long, in ticks, a moment replicant mimics a working echo's job. 0 turns the mimic off.", 200, 0, 1200);
        ECHO_REPLICANT_UNDO_MAX = SpecValues.integer(builder, "echoReplicantUndoMax", "Most blocks a mimicking replicant pulls back from one build (the item goes back to the echo), or stumbles a miner or farmer.", 3, 0, 16);
        ECHO_STRIDER_SHADOW = SpecValues.bool(builder, "echoStriderShadow", "Whether echo striders shadow a working echo like a recorded path, and charge it when its chunk is overloaded.", true);
        ECHO_MAX_PER_PLAYER_CAP = SpecValues.integer(builder, "echoMaxPerPlayerCap", "Most echoes one player may own with chorus slips. Each chorus slip adds one above echoMaxPerPlayer, up to this cap.", 3, 1, 8);
        ECHO_RECORD_BONUS_SECONDS = SpecValues.integer(builder, "echoRecordBonusSeconds", "Seconds each long take slip adds to a recording (a recording never exceeds 60 seconds).", 10, 0, 30);
        ECHO_RECORD_UPGRADE_MAX = SpecValues.integer(builder, "echoRecordUpgradeMax", "How many long take slips one player may absorb.", 2, 0, 5);
        ECHO_STURDY_HEALTH_BONUS = SpecValues.decimal(builder, "echoSturdyHealthBonus", "Max health each sturdy body slip adds to the player's echoes.", 10.0D, 0.0D, 50.0D);
        ECHO_STURDY_UPGRADE_MAX = SpecValues.integer(builder, "echoSturdyUpgradeMax", "How many sturdy body slips one player may absorb.", 2, 0, 5);
        ECHO_FARM_MAX_RADIUS = SpecValues.integer(builder, "echoFarmMaxRadius", "Largest radius a farming echo tends around its work point (the job radius is capped to this). Three blocks up and down are scanned too.", 12, 2, 32);
        ECHO_FARM_POLL_TICKS = SpecValues.integer(builder, "echoFarmPollTicks", "Ticks a farming echo waits between two looks at its field when nothing is ripe.", 100, 20, 1200);
        ECHO_WORK_IMPRINT_EVERY = SpecValues.integer(builder, "echoWorkImprintEvery", "Blocks an echo mines, places or harvests in one chunk before the work leaves a build imprint there (by the owner). 0 turns work imprints off.", 20, 0, 1000);
        ECHO_WORK_INSTABILITY = SpecValues.integer(builder, "echoWorkInstability", "Instability added with each work imprint (on top of the imprint itself).", 3, 0, 50);
        ECHO_MISFIRE_CHANCE = SpecValues.decimal(builder, "echoMisfireChance", "Chance per action that an echo working in an overloaded chunk misfires: a skipped or wrong block (taken back and fixed later), never lost or duplicated items.", 0.15D, 0.0D, 1.0D);
        ECHO_FRACTURE_STOPS = SpecValues.bool(builder, "echoFractureStops", "Whether an echo stops working in a chunk that reached the fracture band.", true);
        ECHO_FOLLOW_LOST_DISTANCE = SpecValues.integer(builder, "echoFollowLostDistance", "Blocks between an echo told to follow and its owner after which it gives up and stays.", 48, 8, 128);
        ECHO_GRAFTS_ENABLED = SpecValues.bool(builder, "echoGraftsEnabled", "Whether an imprint slip (silence, death, fire, fall, explosion) can be grafted into your echo to give it a temper.", true);
        ECHO_GRAFT_CHARGE_SCALE = SpecValues.decimal(builder, "echoGraftChargeScale", "Multiplies the charges one grafted slip gives (hushed 12, grave 24, kindled 32, plunging 24, volatile 48). A graft holds at most two slips' worth.", 1.0D, 0.25D, 4.0D);
        ECHO_GRAFT_AURA_RADIUS = SpecValues.integer(builder, "echoGraftAuraRadius", "Radius, in blocks, in which a hushed echo quiets and a kindled echo smelts for the owner's other echoes. A hushed echo (anyone's) also swallows a residue's or the Scar's act-out within this radius, for one charge.", 8, 0, 16);
        builder.pop();

        SpecValues.section(builder, "residue", "Residual echoes: a loud imprint in an overloaded chunk condenses into a drifting fragment that festers, lashes, and can be read, captured, fed or starved.");
        RESIDUES_ENABLED = SpecValues.bool(builder, "residuesEnabled", "Whether residual echoes condense in overloaded chunks, from released grafts, and in observatory ruins.", true);
        RESIDUE_FORM_CHANCE = SpecValues.decimal(builder, "residueFormChance", "Chance per check (every 10 seconds near a player) that an overloaded chunk condenses its loudest graftable imprint into a residue.", 0.2D, 0.0D, 1.0D);
        RESIDUE_FRACTURE_FORM_CHANCE = SpecValues.decimal(builder, "residueFractureFormChance", "The same chance in a chunk at the fracture band.", 0.5D, 0.0D, 1.0D);
        RESIDUE_FESTER_SECONDS = SpecValues.integer(builder, "residueFesterSeconds", "Seconds between two festers of a residue: it writes its memory back into the chunk, or feeds a matching echo, fades in a calm chunk, or starves under a mute stone.", 60, 10, 600);
        RESIDUE_MAX_NEARBY = SpecValues.integer(builder, "residueMaxNearby", "Most residues within 48 blocks before no new one condenses there.", 3, 1, 16);
        RESIDUE_LASH_RADIUS = SpecValues.decimal(builder, "residueLashRadius", "Blocks within which an unread residue lashes out at a player (half while sneaking).", 3.0D, 0.0D, 8.0D);
        RESIDUE_ACTS_OUT = SpecValues.bool(builder, "residueActsOut", "Whether a residue in a fractured chunk acts its memory out when it festers (a zombie, a fire, a small blast, a lift, darkness). Fire and blasts respect mobGriefing.", true);
        builder.pop();

        SpecValues.section(builder, "relay", "Echo relay: a relay thread links two of your echoes. The link carries hush and kindle auras, residues of the partner's temper, your possession (hop) and what you do while possessing (mirror).");
        RELAY_ENABLED = SpecValues.bool(builder, "relayEnabled", "Whether relay threads can link echoes, and whether existing links do anything. Links stay saved while this is off.", true);
        RELAY_LINK_RANGE = SpecValues.integer(builder, "relayLinkRange", "Blocks within which the second echo must stand from the first when you tie the link. Once tied, the link works at any distance in the same dimension while both ends are loaded.", 16, 2, 64);
        RELAY_HOP_COOLDOWN_SECONDS = SpecValues.integer(builder, "relayHopCooldownSeconds", "Seconds between two relay hops (sneak and press the return key while possessing a linked echo).", 5, 0, 120);
        RELAY_MIRROR = SpecValues.bool(builder, "relayMirror", "Whether a linked echo repeats the blocks you break and place while you possess its partner, at the same offset from its own feet.", true);
        builder.pop();

        SpecValues.section(builder, "vault", "Archive vault: a block that banks imprints drawn out of nearby chunks. What it holds bleeds pressure into its own chunk; a fracture there or an explosion spills it.");
        VAULTS_ENABLED = SpecValues.bool(builder, "vaultsEnabled", "Whether archive vaults draw, bleed, feed echoes and leak. Stored imprints are kept while this is off.", true);
        VAULT_CAPACITY = SpecValues.integer(builder, "vaultCapacity", "Most imprints one vault holds.", 12, 1, 64);
        VAULT_DRAW_SECONDS = SpecValues.integer(builder, "vaultDrawSeconds", "Seconds between two draws of a drawing vault (the loudest imprint from its chunk and the eight around it), and between two echo feeds of an idle one.", 10, 1, 600);
        VAULT_BLEED = SpecValues.decimal(builder, "vaultBleed", "Share of the stored imprints' pressure that bleeds into the vault's own chunk (0.15: twelve deaths add about 49).", 0.15D, 0.0D, 1.0D);
        VAULT_LEAK_SECONDS = SpecValues.integer(builder, "vaultLeakSeconds", "Seconds between two leaks of a filled vault carried in a player's inventory: one of its imprints is written where the carrier stands. 0 turns leaking off.", 60, 0, 3600);
        builder.pop();

        SpecValues.section(builder, "recall", "Living memory, stage 1. A few old gestures can surface again. Nothing here writes a chat line.");
        RECALL_ENABLED = builder.comment("Whether gestures are recorded and whether a replicant or a local flash may show one.").translation("mnemolith.configuration.recallEnabled").define("enabled", true);
        RECALL_MAX_GESTURES = builder.comment("Gestures kept per player. Oldest are dropped first.").translation("mnemolith.configuration.recallMaxGestures").defineInRange("maxGesturesPerPlayer", 48, 8, 128);
        RECALL_MIN_AGE = builder.comment("Ticks a gesture must age before it can be shown. 3600 is three minutes.").translation("mnemolith.configuration.recallMinAge").defineInRange("minAgeTicks", 3600, 200, 72_000);
        RECALL_MAX_AGE = builder.comment("Ticks after which a gesture is dropped. 72000 is one hour.").translation("mnemolith.configuration.recallMaxAge").defineInRange("maxAgeTicks", 72_000, 400, 720_000);
        RECALL_COOLDOWN = builder.comment("Ticks between wow moments for one player, shared by replicant recall and a local flash. 6000 is five minutes.").translation("mnemolith.configuration.recallCooldown").defineInRange("playerCooldownTicks", 6000, 200, 72_000);
        RECALL_CHANCE = builder.comment("Chance, from 0.0 to 1.0, that a replicant near a player with an old enough gesture enters recall instead of copying the last five seconds. Rolled once per replicant per player.").translation("mnemolith.configuration.recallChance").defineInRange("replicantRecallChance", 0.35D, 0.0D, 1.0D);
        RECALL_LOCAL_CHANCE = builder.comment("Chance, checked about every two seconds, that an old gesture within localRadius flashes for that player. A muted chunk at the site never flashes.").translation("mnemolith.configuration.recallLocalChance").defineInRange("localGhostChance", 0.08D, 0.0D, 1.0D);
        RECALL_DISTORTION_CHANCE = builder.comment("Chance a recorded gesture is marked distorted. A local flash of it shifts yaw by 15 degrees and the site by one block. The replicant still uses the stored yaw.").translation("mnemolith.configuration.recallDistortionChance").defineInRange("distortionChance", 0.15D, 0.0D, 1.0D);
        RECALL_RECORD_ATTACKS = builder.comment("Whether a melee attack is stored.").translation("mnemolith.configuration.recallRecordAttacks").define("recordAttacks", true);
        RECALL_RECORD_PLACES = builder.comment("Whether placing a block is stored.").translation("mnemolith.configuration.recallRecordPlaces").define("recordPlaces", true);
        RECALL_RECORD_USES = builder.comment("Whether using a door, trapdoor, gate, lever, or button is stored.").translation("mnemolith.configuration.recallRecordUses").define("recordUses", true);
        RECALL_RECORD_FALLS = builder.comment("Whether a hard fall is stored.").translation("mnemolith.configuration.recallRecordFalls").define("recordFalls", true);
        RECALL_IDLE_TICKS = builder.comment("Ticks a recalling replicant stands and looks before it turns.").translation("mnemolith.configuration.recallIdleTicks").defineInRange("idleTicks", 50, 20, 200);
        RECALL_MATCH_TICKS = builder.comment("Ticks it spends turning to the stored yaw before the gesture.").translation("mnemolith.configuration.recallMatchTicks").defineInRange("matchTicks", 12, 5, 40);
        RECALL_VANISH_TICKS = builder.comment("Ticks after the gesture before it disappears.").translation("mnemolith.configuration.recallVanishTicks").defineInRange("vanishTicks", 30, 10, 80);
        RECALL_LOCAL_RADIUS = builder.comment("Blocks within which an old gesture may flash for the player who made it.").translation("mnemolith.configuration.recallLocalRadius").defineInRange("localRadius", 12, 4, 32);
        RECALL_SKIP_CREATIVE = builder.comment("Whether creative and spectator players are skipped for recall and local flashes. Gestures are still recorded.").translation("mnemolith.configuration.recallSkipCreative").define("skipCreative", true);
        RECALL_SKIP_STORM = builder.comment("Whether a player standing in a recollection storm is skipped for recall and local flashes.").translation("mnemolith.configuration.recallSkipStorm").define("skipDuringStorm", true);
        builder.pop();

        SpecValues.section(builder, "investigate", "Living memory, stage 2. A few places from this play can be read with the raised chronicle lens. Nothing here writes a chat line.");
        INVESTIGATE_ENABLED = builder.comment("Whether this play leaves anchors, and whether the raised lens can name a place.").translation("mnemolith.configuration.investigateEnabled").define("enabled", true);
        INVESTIGATE_MAX_ANCHORS = builder.comment("Anchors kept per player. Gesture traces, recall traces and fractures are dropped first.").translation("mnemolith.configuration.investigateMaxAnchors").defineInRange("maxAnchors", 32, 8, 128);
        INVESTIGATE_MAX_AGE = builder.comment("Ticks after which a fracture or a gesture trace is forgotten. A first death, mute, blank slip, echo and the loudest place stay. 216000 is three hours.").translation("mnemolith.configuration.investigateMaxAge").defineInRange("maxAgeTicks", 216_000, 1_200, 720_000);
        INVESTIGATE_READ_TICKS = builder.comment("Ticks the raised lens must stay on one place before it names that place. 40 is two seconds.").translation("mnemolith.configuration.investigateReadTicks").defineInRange("readTicks", 40, 1, 200);
        INVESTIGATE_READ_RANGE = builder.comment("How far, in blocks, the raised lens looks. A trace is named only when that look lands within two blocks of it.").translation("mnemolith.configuration.investigateReadRange").defineInRange("readRange", 8, 2, 16);
        INVESTIGATE_TRACE_RADIUS = builder.comment("Blocks within which holding the lens shows lingering footsteps at one of your traces.").translation("mnemolith.configuration.investigateTraceRadius").defineInRange("traceRadius", 12, 4, 32);
        INVESTIGATE_LINGER = builder.comment("Ticks those footsteps stay. Longer than a stage-1 flash. 160 is eight seconds.").translation("mnemolith.configuration.investigateLinger").defineInRange("lingerTicks", 160, 20, 600);
        INVESTIGATE_RECORD_DEATH = builder.comment("Whether the first death leaves a trace.").translation("mnemolith.configuration.investigateRecordDeath").define("recordDeath", true);
        INVESTIGATE_RECORD_MUTE = builder.comment("Whether the first mute stone leaves a trace.").translation("mnemolith.configuration.investigateRecordMute").define("recordMute", true);
        INVESTIGATE_RECORD_BLANK = builder.comment("Whether the first blank echo slip leaves a trace.").translation("mnemolith.configuration.investigateRecordBlank").define("recordBlank", true);
        INVESTIGATE_RECORD_ECHO = builder.comment("Whether the first echo met nearby leaves a trace.").translation("mnemolith.configuration.investigateRecordEcho").define("recordEcho", true);
        INVESTIGATE_RECORD_FRACTURE = builder.comment("Whether standing in a chunk as it fractures leaves a trace.").translation("mnemolith.configuration.investigateRecordFracture").define("recordFracture", true);
        INVESTIGATE_RECORD_LOUD = builder.comment("Whether the loudest saturated chunk you have stood in is kept as one trace.").translation("mnemolith.configuration.investigateRecordLoud").define("recordLoud", true);
        INVESTIGATE_RECORD_TRACES = builder.comment("Whether a local flash, a replicant recall, or a finished lens reading of a gesture leaves a trace you can come back to.").translation("mnemolith.configuration.investigateRecordTraces").define("recordTraces", true);
        builder.pop();

        SpecValues.section(builder, "use", "Living memory, stage 3. A place from this play can condense into an offer. Taking, muting, storing or leaving it closes that place. Nothing here writes a chat line.");
        USE_ENABLED = builder.comment("Whether a place from this play can become an offer.").translation("mnemolith.configuration.useEnabled").define("enabled", true);
        USE_MIN_ANCHORS = builder.comment("How many traces this play must already have before a place can condense. The offer itself is chosen from those traces.").translation("mnemolith.configuration.useMinAnchors").defineInRange("minAnchors", 2, 1, 32);
        USE_LIE_CHANCE = builder.comment("Chance, from 0.0 to 1.0, that the silhouette walks to the wrong place, where a replicant is waiting. The residue stays at the true place.").translation("mnemolith.configuration.useLieChance").defineInRange("lieChance", 0.28D, 0.0D, 1.0D);
        USE_LIE_AFTER_LEAVE = builder.comment("The same chance after the player has once walked away from an offer, and for an offer whose source trace was already distorted.").translation("mnemolith.configuration.useLieAfterLeave").defineInRange("lieAfterLeave", 0.75D, 0.0D, 1.0D);
        USE_LIE_OFFSET = builder.comment("Blocks the false place sits from the true one, horizontally, along the trace's facing.").translation("mnemolith.configuration.useLieOffset").defineInRange("lieOffset", 8, 2, 24);
        USE_GUIDE_RANGE = builder.comment("Blocks within which the silhouette may walk, and within which an idle echo with a bearing looks toward the offer.").translation("mnemolith.configuration.useGuideRange").defineInRange("guideRange", 24, 8, 64);
        USE_GUIDE_COOLDOWN = builder.comment("Ticks between two silhouettes for one player while they stay near an offer. 600 is thirty seconds.").translation("mnemolith.configuration.useGuideCooldown").defineInRange("guideCooldown", 600, 40, 72_000);
        USE_CONDENSE_RANGE = builder.comment("Blocks within which standing near the true place lets the residue condense, if the chunk is not muted.").translation("mnemolith.configuration.useCondenseRange").defineInRange("condenseRange", 32, 8, 64);
        USE_WITNESS_RANGE = builder.comment("Blocks within which the player is treated as having stood at the offer. Walking farther than leaveRange after that refuses the place.").translation("mnemolith.configuration.useWitnessRange").defineInRange("witnessRange", 10, 2, 32);
        USE_LEAVE_RANGE = builder.comment("Blocks from a witnessed offer beyond which walking away refuses that spot. The next offer is more likely to lie.").translation("mnemolith.configuration.useLeaveRange").defineInRange("leaveRange", 48, 16, 128);
        USE_STORE_RANGE = builder.comment("Blocks from a legendary residue within which a vault with room can take it, when the player sneaks with an empty hand.").translation("mnemolith.configuration.useStoreRange").defineInRange("storeRange", 8, 2, 32);
        USE_RESIDUE_STRENGTH = builder.comment("Strength of the residue an offer condenses. 4 is a full graft if it is read and taken with the needle.").translation("mnemolith.configuration.useResidueStrength").defineInRange("residueStrength", 4, 1, 6);
        builder.pop();

        SpecValues.section(builder, "intervene", "Living memory, stage 4. A scar fragment used on a block can change the tag of a memory already written there. Nothing here writes a chat line.");
        INTERVENE_ENABLED = builder.comment("Whether a scar fragment used on a block can rewrite an imprint.").translation("mnemolith.configuration.interveneEnabled").define("enabled", true);
        INTERVENE_RANGE = builder.comment("Blocks within which the loudest imprint is rewritten, and within which a scarred echo's temper is read.").translation("mnemolith.configuration.interveneRange").defineInRange("range", 8, 1, 16);
        INTERVENE_ONCE = builder.comment("Whether an imprint that has already been rewritten is left alone. The fragment is not consumed.").translation("mnemolith.configuration.interveneOnce").define("once", true);
        INTERVENE_INSTABILITY = builder.comment("Instability added to the chunk when a tag changes. 0 adds none. The new tag is still scored.").translation("mnemolith.configuration.interveneInstability").defineInRange("instability", 6, 0, 40);
        builder.pop();

        SpecValues.section(builder, "armory", "Armor set bonuses and weapon cooldowns.");
        GRAVE_DAMAGE_MULT = SpecValues.decimal(builder, "graveDamageMult", "Damage multiplier against monsters while wearing a full grave set.", 0.8D, 0.1D, 1.0D);
        GRAVE_SPEED_PENALTY = SpecValues.decimal(builder, "graveSpeedPenalty", "Movement speed multiplier added (usually negative) for a full grave set.", -0.08D, -0.5D, 0.0D);
        HUSH_STEP_BONUS = SpecValues.decimal(builder, "hushStepBonus", "Movement speed multiplier added while sneaking in a full hush set.", 0.12D, 0.0D, 0.5D);
        RECALL_BLADE_COOLDOWN = SpecValues.integer(builder, "recallBladeCooldown", "Ticks the recall blade rests after a second strike.", 30, 5, 200);
        SCAR_BRAND_COOLDOWN = SpecValues.integer(builder, "scarBrandCooldown", "Ticks the scar brand rests after a spend.", 40, 5, 200);
        builder.pop();

        SpecValues.section(builder, "armoryMobs", "Spawn gates for ledger mites, kin witnesses, and fracture stalkers. Eggs and /mnemolith spawn ignore these.");
        STALKER_SPAWN_WEIGHT = SpecValues.integer(builder, "stalkerSpawnWeight", "Chance, out of 100, that a natural fracture stalker spawn attempt is kept. 0 disables natural spawns.", 10, 0, 100);
        STALKER_MIN_PRESSURE = SpecValues.integer(builder, "stalkerMinPressure", "Minimum cached pressure before a fracture stalker can spawn naturally.", 50, 0, 10_000);
        builder.pop();

        SpecValues.section(builder, "sleep", "After a full sleep the house cools. An overloaded chunk can dream a nightmare.");
        SLEEP_CONSOLIDATION = SpecValues.bool(builder, "consolidation", "Whether waking from a full sleep cools quiet memory in the bed chunk.", true);
        SLEEP_COOL_AMOUNT = SpecValues.integer(builder, "coolAmount", "Instability removed from the bed chunk after sleep.", 8, 0, 40);
        SLEEP_FADE_PASSES = SpecValues.integer(builder, "fadePasses", "How many quiet imprints may fade after one sleep.", 2, 0, 8);
        SLEEP_NIGHTMARE = SpecValues.bool(builder, "nightmare", "Whether waking in an overloaded or fractured chunk blinds the player and may spawn a replicant.", true);
        builder.pop();

        SPEC = builder.build();

    }

    private CommonConfig() {}
}
